// GENERATED CODE - DO NOT MODIFY BY HAND
// This file is auto-generated by injectable_generator.
// It will be populated when `build_runner` runs.

// **************************************************************************
// InjectableConfigGenerator
// **************************************************************************

// ignore_for_file: type=lint
// coverage:ignore-file
